defaults:
  - data: custom
  - model: regression_dnn
  - optimizer: adam
  - scheduler: step_lr
  - logger: wandb
  - callback:
    - early_stopping
    - lr_monitor
  - trainer: trainer
hydra:
  run:
    dir: ../logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  